services:
  db:
    container_name: github-mirror-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./packages/db:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5434:5432" # 5434 to avoid conflict with other Postgres instances on this host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - github-mirror

  redis:
    container_name: github-mirror-redis
    image: redis:7-alpine
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - github-mirror

  das:
    container_name: github-mirror-das
    build:
      context: ./packages/das
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:6969:6969"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - github-mirror

networks:
  github-mirror:
    driver: bridge
